platform :ios, '10.0'

target 'MarvelHeroes' do
  
  use_frameworks!
  inhibit_all_warnings!

  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'AZCollectionViewController'
  pod 'CryptoSwift'
  pod 'ReachabilitySwift'
  pod 'SDWebImage'

end
